[package]
name = "authors"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
postgres = "0.19.9"
postgres-types = "0.2.8"
postgresql_embedded = { version = "0.16.3", features = ["blocking", "bundled"] }
refinery = { version = "0.8.14", features = ["postgres"] }
sqlc-core = { version = "0.1.0", path = "../../sqlc-core" }
sqlc-derive = { version = "0.1.0", path = "../../sqlc-derive" }
